service: chill-log

provider:
  name: aws
  region: ap-southeast-2
  runtime: provided.al2
  memorySize: 1024
  timeout: 28
  environment:
    APP_ENV: production
    APP_KEY: ${ssm:/chill-log/app-key}
    LOG_CHANNEL: stderr
    DB_CONNECTION: mysql
    DB_HOST: ${ssm:/chill-log/db-host}
    DB_PORT: 3306
    DB_DATABASE: ${ssm:/chill-log/db-name}
    DB_USERNAME: ${ssm:/chill-log/db-user}
    DB_PASSWORD: ${ssm:/chill-log/db-pass}
    AWS_BUCKET: ${ssm:/chill-log/s3-bucket}
    AWS_REGION: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::${self:provider.environment.AWS_BUCKET}/*

    - Effect: Allow
      Action:
        - rds:DescribeDBInstances
        - rds:Connect
      Resource: "*"

plugins:
  - ./vendor/bref/bref

functions:
  web:
    handler: public/index.php
    description: "Chill-log Laravel API"
    runtime: php-82-fpm
    timeout: 28
    events:
      - httpApi: "*"
    layers:
      - ${bref:layer.php-82-fpm}

# デプロイ時に除外するファイル
package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
    - "!storage/logs/**"
    - "!storage/framework/views/**"
    - "!storage/framework/sessions/**"
